#!/usr/bin/env python3
"""
Generate README.md from README.md.in template.
Inserts auto-generated content like module structure.
"""
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path


def get_module_tree() -> str:
    """Generate module tree dynamically using pypatree."""
    repo_root = Path(__file__).parent.parent

    # Try pypatree with uv (preferred - uses project's venv)
    if shutil.which('uv'):
        try:
            result = subprocess.run(
                ['uv', 'run', 'pypatree', '--docstrings', 'none'],
                capture_output=True,
                text=True,
                cwd=repo_root
            )
            if result.returncode == 0 and result.stdout.strip():
                return f'```\n{result.stdout.strip()}\n```'
        except Exception as e:
            print(f"uv run pypatree failed: {e}", file=sys.stderr)

    # Try pypatree directly (if installed globally/user)
    try:
        result = subprocess.run(
            [sys.executable, '-m', 'pypatree', '--docstrings', 'none'],
            capture_output=True,
            text=True,
            cwd=repo_root,
            env={**os.environ, 'PYTHONPATH': str(repo_root)}
        )
        if result.returncode == 0 and result.stdout.strip():
            return f'```\n{result.stdout.strip()}\n```'
    except Exception as e:
        print(f"pypatree failed: {e}", file=sys.stderr)

    # Fallback: Use filesystem scan
    # This dynamically generates the tree by actually reading the directories
    lines = ['```', 'physio-qc/']

    modules = ['metrics', 'algorithms', 'utils']
    for i, module_dir in enumerate(modules):
        is_last_module = (i == len(modules) - 1)
        module_path = repo_root / module_dir

        if module_path.exists():
            prefix = '└──' if is_last_module else '├──'
            lines.append(f'{prefix} {module_dir}/')

            # List .py files in module (dynamically scanned from filesystem)
            py_files = sorted([f.name for f in module_path.glob('*.py') if f.name != '__init__.py'])
            for j, py_file in enumerate(py_files):
                is_last_file = (j == len(py_files) - 1)
                file_prefix = '    └──' if is_last_file else '    ├──'
                if not is_last_module:
                    file_prefix = '│' + file_prefix
                lines.append(f'{file_prefix} {py_file}')

    lines.append('```')
    return '\n'.join(lines)


def generate_readme():
    """Generate README.md from template."""
    repo_root = Path(__file__).parent.parent
    template_path = repo_root / 'README.md.in'
    output_path = repo_root / 'README.md'

    if not template_path.exists():
        print(f"Error: Template not found at {template_path}", file=sys.stderr)
        sys.exit(1)

    # Read template
    template = template_path.read_text()

    # Generate module tree
    module_tree = get_module_tree()

    # Replace the pypatree section
    pattern = r'<!-- BEGIN PYPATREE -->.*?<!-- END PYPATREE -->'
    replacement = f'<!-- BEGIN PYPATREE -->\n<!-- This section is auto-generated by scripts/generate_readme.py -->\n\n{module_tree}\n\n<!-- END PYPATREE -->'

    readme = re.sub(pattern, replacement, template, flags=re.DOTALL)

    # Write output
    output_path.write_text(readme)
    print(f"✓ Generated {output_path}")


if __name__ == '__main__':
    generate_readme()
