#!/usr/bin/env python3
"""
Generate README.md from README.md.in template.
Inserts auto-generated content like module structure.
"""
import re
import subprocess
import sys
from pathlib import Path


def get_module_tree() -> str:
    """Generate module tree using pypatree."""
    try:
        # Try to run pypatree on each module
        modules = ['metrics', 'algorithms', 'utils']
        output_lines = ['```']

        for module in modules:
            result = subprocess.run(
                [sys.executable, '-m', 'pypatree', module, '--docstrings', 'none'],
                capture_output=True,
                text=True,
                cwd=Path(__file__).parent.parent
            )
            if result.returncode == 0 and result.stdout.strip():
                output_lines.append(result.stdout.strip())

        output_lines.append('```')

        if len(output_lines) > 2:  # More than just the backticks
            return '\n'.join(output_lines)
        else:
            # Fallback to simple structure
            return """```
physio-qc/
├── metrics/          # Signal processing modules
│   ├── ecg.py
│   ├── rsp.py
│   ├── ppg.py
│   └── blood_pressure.py
├── algorithms/       # Specialized algorithms
│   ├── bp_delineator.py
│   └── quality_detection.py
└── utils/           # Utilities
    ├── file_io.py
    ├── peak_editing.py
    └── export.py
```"""
    except Exception as e:
        print(f"Warning: Could not generate module tree: {e}", file=sys.stderr)
        # Fallback structure
        return """```
physio-qc/
├── metrics/          # Signal processing modules
│   ├── ecg.py
│   ├── rsp.py
│   ├── ppg.py
│   └── blood_pressure.py
├── algorithms/       # Specialized algorithms
│   ├── bp_delineator.py
│   └── quality_detection.py
└── utils/           # Utilities
    ├── file_io.py
    ├── peak_editing.py
    └── export.py
```"""


def generate_readme():
    """Generate README.md from template."""
    repo_root = Path(__file__).parent.parent
    template_path = repo_root / 'README.md.in'
    output_path = repo_root / 'README.md'

    if not template_path.exists():
        print(f"Error: Template not found at {template_path}", file=sys.stderr)
        sys.exit(1)

    # Read template
    template = template_path.read_text()

    # Generate module tree
    module_tree = get_module_tree()

    # Replace the pypatree section
    pattern = r'<!-- BEGIN PYPATREE -->.*?<!-- END PYPATREE -->'
    replacement = f'<!-- BEGIN PYPATREE -->\n<!-- This section is auto-generated by scripts/generate_readme.py -->\n\n{module_tree}\n\n<!-- END PYPATREE -->'

    readme = re.sub(pattern, replacement, template, flags=re.DOTALL)

    # Write output
    output_path.write_text(readme)
    print(f"✓ Generated {output_path}")


if __name__ == '__main__':
    generate_readme()
